### ISSUE TITLE
Invalid environment passed to server.js and setup.js

### ISSUE THREAD

**Issue by spnraju** [BaswaS/nightwatch-api-sample#2]
Hi @BaswaS ,

How is that you are passing environments available in nightwatchjs.conf.js to the mentioned files?

if you have followed the example, i am setting up in node process through shell script and reading it from there.

This could not immediately fix your issue. Thats what I noticed on a glance. I will need to spend sometime on your repo.

**Comment by BaswaS** [comment]
Hi @spnraju ,

Thank you for looking into my issue.
The way i pass the env is bit different. Previously in nightwatch-cucumber I was using the envConfig.js file (under config folder). Inside that file I check my env. files and variables based on whichever env i run tests eg integration (.env.int) or staging (.env.stage). I didn't change that part. I could be missing something there. I will also investigate from my end!

Cheers,
Baswa

**Comment by BaswaS** [comment]
Hi @spnraju ,
I've updated env to match with what you have in the example. But I am still facing the same problem. When I run the bash script it just hangs there and doesn't see to do anything. Can you please have a look.
Thanks

**Comment by spnraju** [comment]
#4 should be fixing the issue. Please let me know. There are two basic issues.

1. Paths to feature files, step definitions and support folder are not accurate.
2. The url used to get the status of selenium server is not correct.

These are basic things. I should have find that much earlier. Sorry about that.

**Comment by BaswaS** [comment]
Hi @spnraju ,

Thanks for fix.It's kicking off the tests now. However I see strange behavior in the test run. The test run actually failed but the it reports as passed. Any idea about this ?

**Comment by spnraju** [comment]
Hi @BaswaS I think the tests are running in default environment which is chrome headless and updating the results. I have commentend out the default environment and executed using chrome, Interestingly, they are running in firefox. I tried it with my other repo as well. Same thing happens. I will investigate that and let you know. 

![image](https://user-images.githubusercontent.com/33729221/51948726-a32a8580-244f-11e9-8a22-e52719db7d89.png)

**Comment by BaswaS** [comment]
Hi @spnraju 
yeah I found the same thing. When i change the browser name to ie or something else using execute.sh it doesn't seem to pick it up. 

Also I found one more thing about asynchronous behavior in page objects. Previously when I am using nightwatch-cucumber I just made my functions async/await at step-definition level but now It seems like I have to make my page objects functions as  asynchronous too otherwise they are not running sequentially and I get stale Element error or the test fails  because of wrong state

**Comment by spnraju** [comment]
> Hi @spnraju
> yeah I found the same thing. When i change the browser name to ie or something else using execute.sh it doesn't seem to pick it up.

This seems to be an issue with pure nightwatch itself. I will let you know about it.
> 
> Also I found one more thing about asynchronous behavior in page objects. Previously when I am using nightwatch-cucumber I just made my functions async/await at step-definition level but now It seems like I have to make my page objects functions as asynchronous too otherwise they are not running sequentially and I get stale Element error or the test fails because of wrong state

Not sure about this. I can check and come back on this.

**Comment by BaswaS** [comment]
Hi @spnraju 
Ok..cool

Thanks so much for your time looking into this
